### ISSUE TITLE
New plugin API in v2

### ISSUE THREAD

**Issue by beatfactor** [reallymello/nightwatch-saucelabs-endsauce#4]
Hey,

It would be nice to use the new plugin api which is available in v2. Here's an example plugin: https://github.com/nightwatchjs/vite-plugin-nightwatch

You only need to do 2 things:
1. create a folder `nightwatch` and add a `commands` folder for the custom commands (and/or `assertions` if any custom assertions)
2. to use your new plugin, just add it in the config in the `plugins` array, e.g.:
```js
{
  src_folders: '',
  plugins: ['nightwatch-saucelabs-endsauce ']
}
```

**Comment by reallymello** [comment]
I saw the new plugin api in the release notes and was interested in it, but it wasn't immediately clear to me from the documentation and Vue example what the benefit was over a custom command? Would you be able to clarify, please? I'd like to take advantage of it in 2.0, but I wasn't sure what the advantages or differences were.

**Comment by beatfactor** [comment]
It's mostly for having a common format for plugin developers with which to export custom commands/assertions. And we also aim to make it easier for users to install and use the plugins, so for instance they will just use it by simply adding it to the `plugins` list and the custom commands will be automatically discovered.

**Comment by reallymello** [comment]
@beatfactor as of v2.0 migrated to use the plugin pattern. Noted in the README that users still on custom_commands_path will have to update their path to avoid confusion. Thanks for the suggestion. We are all plugged in.
